[package]
name = "crud_with_rust_sqlite"
version = "0.1.0"
edition = "2021"
authors=["Eslam Muhammad <0xCrypt00o@protonmail.com>"]



[dependencies]
tokio={version="1.26.0",features=["full"]}
dotenv="0.15"
sqlx={version="0.6",features=["sqlite","runtime-tokio-native-tls"]}

